import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_layout/Header";
import Footer from "./_layout/Footer";
import ProviderCart from "./provider/ProviderCart";
import { Toaster } from "react-hot-toast";
import { SessionProviderClient } from "./provider/sessionProviderClient";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inter.variable} antialiased`}>
        <SessionProviderClient>
          <Toaster position="top-right" containerClassName="mt-4" />
          <ProviderCart>
            <Header />
            {children}
            <Footer />
          </ProviderCart>
        </SessionProviderClient>
      </body>
    </html>
  );
}
